// 2. Aims (max 1 page)
// State main aim(s) and sub-aims. If part of a larger project, state this.

= Aims

The overall aim of this thesis was to ...

+ *Main aim 1:* ...
+ *Main aim 2:* ...
  + Sub-aim 2a: ...
  + Sub-aim 2b: ...
